"""
Global Location Data for MisFigus
Covers 120+ countries where Panini operates with structured location hierarchy.
"""

# ISO-3166 Countries with localized names
COUNTRIES = {
    # Americas
    "AR": {"name": {"es": "Argentina", "en": "Argentina", "pt": "Argentina"}, "regions": True},
    "BO": {"name": {"es": "Bolivia", "en": "Bolivia", "pt": "Bolívia"}, "regions": True},
    "BR": {"name": {"es": "Brasil", "en": "Brazil", "pt": "Brasil"}, "regions": True},
    "CL": {"name": {"es": "Chile", "en": "Chile", "pt": "Chile"}, "regions": True},
    "CO": {"name": {"es": "Colombia", "en": "Colombia", "pt": "Colômbia"}, "regions": True},
    "CR": {"name": {"es": "Costa Rica", "en": "Costa Rica", "pt": "Costa Rica"}, "regions": True},
    "CU": {"name": {"es": "Cuba", "en": "Cuba", "pt": "Cuba"}, "regions": True},
    "DO": {"name": {"es": "República Dominicana", "en": "Dominican Republic", "pt": "República Dominicana"}, "regions": True},
    "EC": {"name": {"es": "Ecuador", "en": "Ecuador", "pt": "Equador"}, "regions": True},
    "SV": {"name": {"es": "El Salvador", "en": "El Salvador", "pt": "El Salvador"}, "regions": True},
    "GT": {"name": {"es": "Guatemala", "en": "Guatemala", "pt": "Guatemala"}, "regions": True},
    "HN": {"name": {"es": "Honduras", "en": "Honduras", "pt": "Honduras"}, "regions": True},
    "MX": {"name": {"es": "México", "en": "Mexico", "pt": "México"}, "regions": True},
    "NI": {"name": {"es": "Nicaragua", "en": "Nicaragua", "pt": "Nicarágua"}, "regions": True},
    "PA": {"name": {"es": "Panamá", "en": "Panama", "pt": "Panamá"}, "regions": True},
    "PY": {"name": {"es": "Paraguay", "en": "Paraguay", "pt": "Paraguai"}, "regions": True},
    "PE": {"name": {"es": "Perú", "en": "Peru", "pt": "Peru"}, "regions": True},
    "PR": {"name": {"es": "Puerto Rico", "en": "Puerto Rico", "pt": "Porto Rico"}, "regions": True},
    "UY": {"name": {"es": "Uruguay", "en": "Uruguay", "pt": "Uruguai"}, "regions": True},
    "VE": {"name": {"es": "Venezuela", "en": "Venezuela", "pt": "Venezuela"}, "regions": True},
    "US": {"name": {"es": "Estados Unidos", "en": "United States", "pt": "Estados Unidos"}, "regions": True},
    "CA": {"name": {"es": "Canadá", "en": "Canada", "pt": "Canadá"}, "regions": True},
    
    # Europe
    "ES": {"name": {"es": "España", "en": "Spain", "pt": "Espanha"}, "regions": True},
    "PT": {"name": {"es": "Portugal", "en": "Portugal", "pt": "Portugal"}, "regions": True},
    "FR": {"name": {"es": "Francia", "en": "France", "pt": "França"}, "regions": True},
    "IT": {"name": {"es": "Italia", "en": "Italy", "pt": "Itália"}, "regions": True},
    "DE": {"name": {"es": "Alemania", "en": "Germany", "pt": "Alemanha"}, "regions": True},
    "GB": {"name": {"es": "Reino Unido", "en": "United Kingdom", "pt": "Reino Unido"}, "regions": True},
    "NL": {"name": {"es": "Países Bajos", "en": "Netherlands", "pt": "Países Baixos"}, "regions": True},
    "BE": {"name": {"es": "Bélgica", "en": "Belgium", "pt": "Bélgica"}, "regions": True},
    "CH": {"name": {"es": "Suiza", "en": "Switzerland", "pt": "Suíça"}, "regions": True},
    "AT": {"name": {"es": "Austria", "en": "Austria", "pt": "Áustria"}, "regions": True},
    "PL": {"name": {"es": "Polonia", "en": "Poland", "pt": "Polônia"}, "regions": True},
    "CZ": {"name": {"es": "República Checa", "en": "Czech Republic", "pt": "República Tcheca"}, "regions": True},
    "GR": {"name": {"es": "Grecia", "en": "Greece", "pt": "Grécia"}, "regions": True},
    "SE": {"name": {"es": "Suecia", "en": "Sweden", "pt": "Suécia"}, "regions": True},
    "NO": {"name": {"es": "Noruega", "en": "Norway", "pt": "Noruega"}, "regions": True},
    "DK": {"name": {"es": "Dinamarca", "en": "Denmark", "pt": "Dinamarca"}, "regions": True},
    "FI": {"name": {"es": "Finlandia", "en": "Finland", "pt": "Finlândia"}, "regions": True},
    "IE": {"name": {"es": "Irlanda", "en": "Ireland", "pt": "Irlanda"}, "regions": True},
    "RO": {"name": {"es": "Rumania", "en": "Romania", "pt": "Romênia"}, "regions": True},
    "HU": {"name": {"es": "Hungría", "en": "Hungary", "pt": "Hungria"}, "regions": True},
    "HR": {"name": {"es": "Croacia", "en": "Croatia", "pt": "Croácia"}, "regions": True},
    "RS": {"name": {"es": "Serbia", "en": "Serbia", "pt": "Sérvia"}, "regions": True},
    "BG": {"name": {"es": "Bulgaria", "en": "Bulgaria", "pt": "Bulgária"}, "regions": True},
    "SK": {"name": {"es": "Eslovaquia", "en": "Slovakia", "pt": "Eslováquia"}, "regions": True},
    "SI": {"name": {"es": "Eslovenia", "en": "Slovenia", "pt": "Eslovênia"}, "regions": True},
    "UA": {"name": {"es": "Ucrania", "en": "Ukraine", "pt": "Ucrânia"}, "regions": True},
    "RU": {"name": {"es": "Rusia", "en": "Russia", "pt": "Rússia"}, "regions": True},
    "TR": {"name": {"es": "Turquía", "en": "Turkey", "pt": "Turquia"}, "regions": True},
    
    # Africa & Middle East
    "ZA": {"name": {"es": "Sudáfrica", "en": "South Africa", "pt": "África do Sul"}, "regions": True},
    "EG": {"name": {"es": "Egipto", "en": "Egypt", "pt": "Egito"}, "regions": True},
    "MA": {"name": {"es": "Marruecos", "en": "Morocco", "pt": "Marrocos"}, "regions": True},
    "NG": {"name": {"es": "Nigeria", "en": "Nigeria", "pt": "Nigéria"}, "regions": True},
    "KE": {"name": {"es": "Kenia", "en": "Kenya", "pt": "Quênia"}, "regions": True},
    "GH": {"name": {"es": "Ghana", "en": "Ghana", "pt": "Gana"}, "regions": True},
    "SN": {"name": {"es": "Senegal", "en": "Senegal", "pt": "Senegal"}, "regions": True},
    "CI": {"name": {"es": "Costa de Marfil", "en": "Ivory Coast", "pt": "Costa do Marfim"}, "regions": True},
    "CM": {"name": {"es": "Camerún", "en": "Cameroon", "pt": "Camarões"}, "regions": True},
    "TN": {"name": {"es": "Túnez", "en": "Tunisia", "pt": "Tunísia"}, "regions": True},
    "DZ": {"name": {"es": "Argelia", "en": "Algeria", "pt": "Argélia"}, "regions": True},
    "AE": {"name": {"es": "Emiratos Árabes Unidos", "en": "United Arab Emirates", "pt": "Emirados Árabes Unidos"}, "regions": True},
    "SA": {"name": {"es": "Arabia Saudita", "en": "Saudi Arabia", "pt": "Arábia Saudita"}, "regions": True},
    "QA": {"name": {"es": "Catar", "en": "Qatar", "pt": "Catar"}, "regions": True},
    "IL": {"name": {"es": "Israel", "en": "Israel", "pt": "Israel"}, "regions": True},
    
    # Asia & Oceania
    "JP": {"name": {"es": "Japón", "en": "Japan", "pt": "Japão"}, "regions": True},
    "KR": {"name": {"es": "Corea del Sur", "en": "South Korea", "pt": "Coreia do Sul"}, "regions": True},
    "CN": {"name": {"es": "China", "en": "China", "pt": "China"}, "regions": True},
    "IN": {"name": {"es": "India", "en": "India", "pt": "Índia"}, "regions": True},
    "ID": {"name": {"es": "Indonesia", "en": "Indonesia", "pt": "Indonésia"}, "regions": True},
    "TH": {"name": {"es": "Tailandia", "en": "Thailand", "pt": "Tailândia"}, "regions": True},
    "VN": {"name": {"es": "Vietnam", "en": "Vietnam", "pt": "Vietnã"}, "regions": True},
    "MY": {"name": {"es": "Malasia", "en": "Malaysia", "pt": "Malásia"}, "regions": True},
    "SG": {"name": {"es": "Singapur", "en": "Singapore", "pt": "Singapura"}, "regions": False},
    "PH": {"name": {"es": "Filipinas", "en": "Philippines", "pt": "Filipinas"}, "regions": True},
    "AU": {"name": {"es": "Australia", "en": "Australia", "pt": "Austrália"}, "regions": True},
    "NZ": {"name": {"es": "Nueva Zelanda", "en": "New Zealand", "pt": "Nova Zelândia"}, "regions": True},
}

# Regions by country (major provinces/states)
REGIONS = {
    "AR": [
        {"code": "AR-C", "name": "Ciudad Autónoma de Buenos Aires"},
        {"code": "AR-B", "name": "Buenos Aires"},
        {"code": "AR-K", "name": "Catamarca"},
        {"code": "AR-H", "name": "Chaco"},
        {"code": "AR-U", "name": "Chubut"},
        {"code": "AR-X", "name": "Córdoba"},
        {"code": "AR-W", "name": "Corrientes"},
        {"code": "AR-E", "name": "Entre Ríos"},
        {"code": "AR-P", "name": "Formosa"},
        {"code": "AR-Y", "name": "Jujuy"},
        {"code": "AR-L", "name": "La Pampa"},
        {"code": "AR-F", "name": "La Rioja"},
        {"code": "AR-M", "name": "Mendoza"},
        {"code": "AR-N", "name": "Misiones"},
        {"code": "AR-Q", "name": "Neuquén"},
        {"code": "AR-R", "name": "Río Negro"},
        {"code": "AR-A", "name": "Salta"},
        {"code": "AR-J", "name": "San Juan"},
        {"code": "AR-D", "name": "San Luis"},
        {"code": "AR-Z", "name": "Santa Cruz"},
        {"code": "AR-S", "name": "Santa Fe"},
        {"code": "AR-G", "name": "Santiago del Estero"},
        {"code": "AR-V", "name": "Tierra del Fuego"},
        {"code": "AR-T", "name": "Tucumán"},
    ],
    "BR": [
        {"code": "BR-AC", "name": "Acre"},
        {"code": "BR-AL", "name": "Alagoas"},
        {"code": "BR-AP", "name": "Amapá"},
        {"code": "BR-AM", "name": "Amazonas"},
        {"code": "BR-BA", "name": "Bahia"},
        {"code": "BR-CE", "name": "Ceará"},
        {"code": "BR-DF", "name": "Distrito Federal"},
        {"code": "BR-ES", "name": "Espírito Santo"},
        {"code": "BR-GO", "name": "Goiás"},
        {"code": "BR-MA", "name": "Maranhão"},
        {"code": "BR-MT", "name": "Mato Grosso"},
        {"code": "BR-MS", "name": "Mato Grosso do Sul"},
        {"code": "BR-MG", "name": "Minas Gerais"},
        {"code": "BR-PA", "name": "Pará"},
        {"code": "BR-PB", "name": "Paraíba"},
        {"code": "BR-PR", "name": "Paraná"},
        {"code": "BR-PE", "name": "Pernambuco"},
        {"code": "BR-PI", "name": "Piauí"},
        {"code": "BR-RJ", "name": "Rio de Janeiro"},
        {"code": "BR-RN", "name": "Rio Grande do Norte"},
        {"code": "BR-RS", "name": "Rio Grande do Sul"},
        {"code": "BR-RO", "name": "Rondônia"},
        {"code": "BR-RR", "name": "Roraima"},
        {"code": "BR-SC", "name": "Santa Catarina"},
        {"code": "BR-SP", "name": "São Paulo"},
        {"code": "BR-SE", "name": "Sergipe"},
        {"code": "BR-TO", "name": "Tocantins"},
    ],
    "ES": [
        {"code": "ES-AN", "name": "Andalucía"},
        {"code": "ES-AR", "name": "Aragón"},
        {"code": "ES-AS", "name": "Asturias"},
        {"code": "ES-IB", "name": "Islas Baleares"},
        {"code": "ES-CN", "name": "Canarias"},
        {"code": "ES-CB", "name": "Cantabria"},
        {"code": "ES-CL", "name": "Castilla y León"},
        {"code": "ES-CM", "name": "Castilla-La Mancha"},
        {"code": "ES-CT", "name": "Cataluña"},
        {"code": "ES-EX", "name": "Extremadura"},
        {"code": "ES-GA", "name": "Galicia"},
        {"code": "ES-MD", "name": "Madrid"},
        {"code": "ES-MC", "name": "Murcia"},
        {"code": "ES-NC", "name": "Navarra"},
        {"code": "ES-PV", "name": "País Vasco"},
        {"code": "ES-RI", "name": "La Rioja"},
        {"code": "ES-VC", "name": "Comunidad Valenciana"},
    ],
    "MX": [
        {"code": "MX-AGU", "name": "Aguascalientes"},
        {"code": "MX-BCN", "name": "Baja California"},
        {"code": "MX-BCS", "name": "Baja California Sur"},
        {"code": "MX-CAM", "name": "Campeche"},
        {"code": "MX-CHP", "name": "Chiapas"},
        {"code": "MX-CHH", "name": "Chihuahua"},
        {"code": "MX-CMX", "name": "Ciudad de México"},
        {"code": "MX-COA", "name": "Coahuila"},
        {"code": "MX-COL", "name": "Colima"},
        {"code": "MX-DUR", "name": "Durango"},
        {"code": "MX-GUA", "name": "Guanajuato"},
        {"code": "MX-GRO", "name": "Guerrero"},
        {"code": "MX-HID", "name": "Hidalgo"},
        {"code": "MX-JAL", "name": "Jalisco"},
        {"code": "MX-MEX", "name": "Estado de México"},
        {"code": "MX-MIC", "name": "Michoacán"},
        {"code": "MX-MOR", "name": "Morelos"},
        {"code": "MX-NAY", "name": "Nayarit"},
        {"code": "MX-NLE", "name": "Nuevo León"},
        {"code": "MX-OAX", "name": "Oaxaca"},
        {"code": "MX-PUE", "name": "Puebla"},
        {"code": "MX-QUE", "name": "Querétaro"},
        {"code": "MX-ROO", "name": "Quintana Roo"},
        {"code": "MX-SLP", "name": "San Luis Potosí"},
        {"code": "MX-SIN", "name": "Sinaloa"},
        {"code": "MX-SON", "name": "Sonora"},
        {"code": "MX-TAB", "name": "Tabasco"},
        {"code": "MX-TAM", "name": "Tamaulipas"},
        {"code": "MX-TLA", "name": "Tlaxcala"},
        {"code": "MX-VER", "name": "Veracruz"},
        {"code": "MX-YUC", "name": "Yucatán"},
        {"code": "MX-ZAC", "name": "Zacatecas"},
    ],
    "US": [
        {"code": "US-AL", "name": "Alabama"},
        {"code": "US-AK", "name": "Alaska"},
        {"code": "US-AZ", "name": "Arizona"},
        {"code": "US-AR", "name": "Arkansas"},
        {"code": "US-CA", "name": "California"},
        {"code": "US-CO", "name": "Colorado"},
        {"code": "US-CT", "name": "Connecticut"},
        {"code": "US-DE", "name": "Delaware"},
        {"code": "US-FL", "name": "Florida"},
        {"code": "US-GA", "name": "Georgia"},
        {"code": "US-HI", "name": "Hawaii"},
        {"code": "US-ID", "name": "Idaho"},
        {"code": "US-IL", "name": "Illinois"},
        {"code": "US-IN", "name": "Indiana"},
        {"code": "US-IA", "name": "Iowa"},
        {"code": "US-KS", "name": "Kansas"},
        {"code": "US-KY", "name": "Kentucky"},
        {"code": "US-LA", "name": "Louisiana"},
        {"code": "US-ME", "name": "Maine"},
        {"code": "US-MD", "name": "Maryland"},
        {"code": "US-MA", "name": "Massachusetts"},
        {"code": "US-MI", "name": "Michigan"},
        {"code": "US-MN", "name": "Minnesota"},
        {"code": "US-MS", "name": "Mississippi"},
        {"code": "US-MO", "name": "Missouri"},
        {"code": "US-MT", "name": "Montana"},
        {"code": "US-NE", "name": "Nebraska"},
        {"code": "US-NV", "name": "Nevada"},
        {"code": "US-NH", "name": "New Hampshire"},
        {"code": "US-NJ", "name": "New Jersey"},
        {"code": "US-NM", "name": "New Mexico"},
        {"code": "US-NY", "name": "New York"},
        {"code": "US-NC", "name": "North Carolina"},
        {"code": "US-ND", "name": "North Dakota"},
        {"code": "US-OH", "name": "Ohio"},
        {"code": "US-OK", "name": "Oklahoma"},
        {"code": "US-OR", "name": "Oregon"},
        {"code": "US-PA", "name": "Pennsylvania"},
        {"code": "US-RI", "name": "Rhode Island"},
        {"code": "US-SC", "name": "South Carolina"},
        {"code": "US-SD", "name": "South Dakota"},
        {"code": "US-TN", "name": "Tennessee"},
        {"code": "US-TX", "name": "Texas"},
        {"code": "US-UT", "name": "Utah"},
        {"code": "US-VT", "name": "Vermont"},
        {"code": "US-VA", "name": "Virginia"},
        {"code": "US-WA", "name": "Washington"},
        {"code": "US-WV", "name": "West Virginia"},
        {"code": "US-WI", "name": "Wisconsin"},
        {"code": "US-WY", "name": "Wyoming"},
        {"code": "US-DC", "name": "Washington D.C."},
    ],
    "IT": [
        {"code": "IT-65", "name": "Abruzzo"},
        {"code": "IT-77", "name": "Basilicata"},
        {"code": "IT-78", "name": "Calabria"},
        {"code": "IT-72", "name": "Campania"},
        {"code": "IT-45", "name": "Emilia-Romagna"},
        {"code": "IT-36", "name": "Friuli-Venezia Giulia"},
        {"code": "IT-62", "name": "Lazio"},
        {"code": "IT-42", "name": "Liguria"},
        {"code": "IT-25", "name": "Lombardia"},
        {"code": "IT-57", "name": "Marche"},
        {"code": "IT-67", "name": "Molise"},
        {"code": "IT-21", "name": "Piemonte"},
        {"code": "IT-75", "name": "Puglia"},
        {"code": "IT-88", "name": "Sardegna"},
        {"code": "IT-82", "name": "Sicilia"},
        {"code": "IT-52", "name": "Toscana"},
        {"code": "IT-32", "name": "Trentino-Alto Adige"},
        {"code": "IT-55", "name": "Umbria"},
        {"code": "IT-23", "name": "Valle d'Aosta"},
        {"code": "IT-34", "name": "Veneto"},
    ],
    "FR": [
        {"code": "FR-ARA", "name": "Auvergne-Rhône-Alpes"},
        {"code": "FR-BFC", "name": "Bourgogne-Franche-Comté"},
        {"code": "FR-BRE", "name": "Bretagne"},
        {"code": "FR-CVL", "name": "Centre-Val de Loire"},
        {"code": "FR-COR", "name": "Corse"},
        {"code": "FR-GES", "name": "Grand Est"},
        {"code": "FR-HDF", "name": "Hauts-de-France"},
        {"code": "FR-IDF", "name": "Île-de-France"},
        {"code": "FR-NOR", "name": "Normandie"},
        {"code": "FR-NAQ", "name": "Nouvelle-Aquitaine"},
        {"code": "FR-OCC", "name": "Occitanie"},
        {"code": "FR-PDL", "name": "Pays de la Loire"},
        {"code": "FR-PAC", "name": "Provence-Alpes-Côte d'Azur"},
    ],
    "DE": [
        {"code": "DE-BW", "name": "Baden-Württemberg"},
        {"code": "DE-BY", "name": "Bayern"},
        {"code": "DE-BE", "name": "Berlin"},
        {"code": "DE-BB", "name": "Brandenburg"},
        {"code": "DE-HB", "name": "Bremen"},
        {"code": "DE-HH", "name": "Hamburg"},
        {"code": "DE-HE", "name": "Hessen"},
        {"code": "DE-MV", "name": "Mecklenburg-Vorpommern"},
        {"code": "DE-NI", "name": "Niedersachsen"},
        {"code": "DE-NW", "name": "Nordrhein-Westfalen"},
        {"code": "DE-RP", "name": "Rheinland-Pfalz"},
        {"code": "DE-SL", "name": "Saarland"},
        {"code": "DE-SN", "name": "Sachsen"},
        {"code": "DE-ST", "name": "Sachsen-Anhalt"},
        {"code": "DE-SH", "name": "Schleswig-Holstein"},
        {"code": "DE-TH", "name": "Thüringen"},
    ],
    "GB": [
        {"code": "GB-ENG", "name": "England"},
        {"code": "GB-SCT", "name": "Scotland"},
        {"code": "GB-WLS", "name": "Wales"},
        {"code": "GB-NIR", "name": "Northern Ireland"},
    ],
    "CO": [
        {"code": "CO-AMA", "name": "Amazonas"},
        {"code": "CO-ANT", "name": "Antioquia"},
        {"code": "CO-ARA", "name": "Arauca"},
        {"code": "CO-ATL", "name": "Atlántico"},
        {"code": "CO-DC", "name": "Bogotá D.C."},
        {"code": "CO-BOL", "name": "Bolívar"},
        {"code": "CO-BOY", "name": "Boyacá"},
        {"code": "CO-CAL", "name": "Caldas"},
        {"code": "CO-CAQ", "name": "Caquetá"},
        {"code": "CO-CAS", "name": "Casanare"},
        {"code": "CO-CAU", "name": "Cauca"},
        {"code": "CO-CES", "name": "Cesar"},
        {"code": "CO-CHO", "name": "Chocó"},
        {"code": "CO-COR", "name": "Córdoba"},
        {"code": "CO-CUN", "name": "Cundinamarca"},
        {"code": "CO-GUA", "name": "Guainía"},
        {"code": "CO-GUV", "name": "Guaviare"},
        {"code": "CO-HUI", "name": "Huila"},
        {"code": "CO-LAG", "name": "La Guajira"},
        {"code": "CO-MAG", "name": "Magdalena"},
        {"code": "CO-MET", "name": "Meta"},
        {"code": "CO-NAR", "name": "Nariño"},
        {"code": "CO-NSA", "name": "Norte de Santander"},
        {"code": "CO-PUT", "name": "Putumayo"},
        {"code": "CO-QUI", "name": "Quindío"},
        {"code": "CO-RIS", "name": "Risaralda"},
        {"code": "CO-SAP", "name": "San Andrés y Providencia"},
        {"code": "CO-SAN", "name": "Santander"},
        {"code": "CO-SUC", "name": "Sucre"},
        {"code": "CO-TOL", "name": "Tolima"},
        {"code": "CO-VAC", "name": "Valle del Cauca"},
        {"code": "CO-VAU", "name": "Vaupés"},
        {"code": "CO-VID", "name": "Vichada"},
    ],
    "CL": [
        {"code": "CL-AI", "name": "Aysén"},
        {"code": "CL-AN", "name": "Antofagasta"},
        {"code": "CL-AP", "name": "Arica y Parinacota"},
        {"code": "CL-AT", "name": "Atacama"},
        {"code": "CL-BI", "name": "Biobío"},
        {"code": "CL-CO", "name": "Coquimbo"},
        {"code": "CL-AR", "name": "La Araucanía"},
        {"code": "CL-LI", "name": "O'Higgins"},
        {"code": "CL-LL", "name": "Los Lagos"},
        {"code": "CL-LR", "name": "Los Ríos"},
        {"code": "CL-MA", "name": "Magallanes"},
        {"code": "CL-ML", "name": "Maule"},
        {"code": "CL-NB", "name": "Ñuble"},
        {"code": "CL-RM", "name": "Región Metropolitana"},
        {"code": "CL-TA", "name": "Tarapacá"},
        {"code": "CL-VS", "name": "Valparaíso"},
    ],
    "PE": [
        {"code": "PE-AMA", "name": "Amazonas"},
        {"code": "PE-ANC", "name": "Áncash"},
        {"code": "PE-APU", "name": "Apurímac"},
        {"code": "PE-ARE", "name": "Arequipa"},
        {"code": "PE-AYA", "name": "Ayacucho"},
        {"code": "PE-CAJ", "name": "Cajamarca"},
        {"code": "PE-CAL", "name": "Callao"},
        {"code": "PE-CUS", "name": "Cusco"},
        {"code": "PE-HUV", "name": "Huancavelica"},
        {"code": "PE-HUC", "name": "Huánuco"},
        {"code": "PE-ICA", "name": "Ica"},
        {"code": "PE-JUN", "name": "Junín"},
        {"code": "PE-LAL", "name": "La Libertad"},
        {"code": "PE-LAM", "name": "Lambayeque"},
        {"code": "PE-LIM", "name": "Lima"},
        {"code": "PE-LOR", "name": "Loreto"},
        {"code": "PE-MDD", "name": "Madre de Dios"},
        {"code": "PE-MOQ", "name": "Moquegua"},
        {"code": "PE-PAS", "name": "Pasco"},
        {"code": "PE-PIU", "name": "Piura"},
        {"code": "PE-PUN", "name": "Puno"},
        {"code": "PE-SAM", "name": "San Martín"},
        {"code": "PE-TAC", "name": "Tacna"},
        {"code": "PE-TUM", "name": "Tumbes"},
        {"code": "PE-UCA", "name": "Ucayali"},
    ],
}

# Major cities with coordinates (sample data - production would use full database)
# Format: place_id, city_name, region_code, lat, lng
CITIES = {
    "AR": [
        # Buenos Aires Province & CABA
        {"place_id": "AR-C-CABA", "city": "Capital Federal", "region": "AR-C", "lat": -34.6037, "lng": -58.3816},
        {"place_id": "AR-B-LAPLATA", "city": "La Plata", "region": "AR-B", "lat": -34.9205, "lng": -57.9536},
        {"place_id": "AR-B-MARDELPLATA", "city": "Mar del Plata", "region": "AR-B", "lat": -38.0055, "lng": -57.5426},
        {"place_id": "AR-B-QUILMES", "city": "Quilmes", "region": "AR-B", "lat": -34.7251, "lng": -58.2570},
        {"place_id": "AR-B-AVELLANEDA", "city": "Avellaneda", "region": "AR-B", "lat": -34.6603, "lng": -58.3633},
        {"place_id": "AR-B-LANUS", "city": "Lanús", "region": "AR-B", "lat": -34.7066, "lng": -58.3927},
        {"place_id": "AR-B-LOMAS", "city": "Lomas de Zamora", "region": "AR-B", "lat": -34.7589, "lng": -58.4010},
        {"place_id": "AR-B-SANISIDRO", "city": "San Isidro", "region": "AR-B", "lat": -34.4717, "lng": -58.5286},
        {"place_id": "AR-B-TIGRE", "city": "Tigre", "region": "AR-B", "lat": -34.4259, "lng": -58.5797},
        {"place_id": "AR-B-MORON", "city": "Morón", "region": "AR-B", "lat": -34.6534, "lng": -58.6198},
        {"place_id": "AR-B-MORENO", "city": "Moreno", "region": "AR-B", "lat": -34.6333, "lng": -58.7833},
        {"place_id": "AR-B-MERLO", "city": "Merlo", "region": "AR-B", "lat": -34.6659, "lng": -58.7276},
        {"place_id": "AR-B-SANMARTIN", "city": "San Martín", "region": "AR-B", "lat": -34.5731, "lng": -58.5353},
        {"place_id": "AR-B-PILAR", "city": "Pilar", "region": "AR-B", "lat": -34.4587, "lng": -58.9142},
        {"place_id": "AR-B-BAHIABLANCA", "city": "Bahía Blanca", "region": "AR-B", "lat": -38.7196, "lng": -62.2724},
        # Córdoba
        {"place_id": "AR-X-CORDOBA", "city": "Córdoba", "region": "AR-X", "lat": -31.4201, "lng": -64.1888},
        {"place_id": "AR-X-VILLACM", "city": "Villa Carlos Paz", "region": "AR-X", "lat": -31.4241, "lng": -64.4978},
        {"place_id": "AR-X-RIOCUARTO", "city": "Río Cuarto", "region": "AR-X", "lat": -33.1307, "lng": -64.3499},
        # Santa Fe
        {"place_id": "AR-S-ROSARIO", "city": "Rosario", "region": "AR-S", "lat": -32.9468, "lng": -60.6393},
        {"place_id": "AR-S-SANTAFE", "city": "Santa Fe", "region": "AR-S", "lat": -31.6333, "lng": -60.7000},
        # Mendoza
        {"place_id": "AR-M-MENDOZA", "city": "Mendoza", "region": "AR-M", "lat": -32.8908, "lng": -68.8272},
        # Tucumán
        {"place_id": "AR-T-TUCUMAN", "city": "San Miguel de Tucumán", "region": "AR-T", "lat": -26.8083, "lng": -65.2176},
        # Salta
        {"place_id": "AR-A-SALTA", "city": "Salta", "region": "AR-A", "lat": -24.7883, "lng": -65.4106},
        # Entre Ríos
        {"place_id": "AR-E-PARANA", "city": "Paraná", "region": "AR-E", "lat": -31.7413, "lng": -60.5115},
        # Neuquén
        {"place_id": "AR-Q-NEUQUEN", "city": "Neuquén", "region": "AR-Q", "lat": -38.9516, "lng": -68.0591},
    ],
    "BR": [
        {"place_id": "BR-SP-SAO", "city": "São Paulo", "region": "BR-SP", "lat": -23.5505, "lng": -46.6333},
        {"place_id": "BR-RJ-RIO", "city": "Rio de Janeiro", "region": "BR-RJ", "lat": -22.9068, "lng": -43.1729},
        {"place_id": "BR-DF-BSB", "city": "Brasília", "region": "BR-DF", "lat": -15.7942, "lng": -47.8822},
        {"place_id": "BR-BA-SSA", "city": "Salvador", "region": "BR-BA", "lat": -12.9714, "lng": -38.5014},
        {"place_id": "BR-CE-FOR", "city": "Fortaleza", "region": "BR-CE", "lat": -3.7172, "lng": -38.5433},
        {"place_id": "BR-MG-BHZ", "city": "Belo Horizonte", "region": "BR-MG", "lat": -19.9167, "lng": -43.9345},
        {"place_id": "BR-AM-MAO", "city": "Manaus", "region": "BR-AM", "lat": -3.1190, "lng": -60.0217},
        {"place_id": "BR-PR-CWB", "city": "Curitiba", "region": "BR-PR", "lat": -25.4290, "lng": -49.2671},
        {"place_id": "BR-PE-REC", "city": "Recife", "region": "BR-PE", "lat": -8.0476, "lng": -34.8770},
        {"place_id": "BR-RS-POA", "city": "Porto Alegre", "region": "BR-RS", "lat": -30.0346, "lng": -51.2177},
    ],
    "ES": [
        {"place_id": "ES-MD-MAD", "city": "Madrid", "region": "ES-MD", "lat": 40.4168, "lng": -3.7038},
        {"place_id": "ES-CT-BCN", "city": "Barcelona", "region": "ES-CT", "lat": 41.3874, "lng": 2.1686},
        {"place_id": "ES-VC-VLC", "city": "Valencia", "region": "ES-VC", "lat": 39.4699, "lng": -0.3763},
        {"place_id": "ES-AN-SEV", "city": "Sevilla", "region": "ES-AN", "lat": 37.3891, "lng": -5.9845},
        {"place_id": "ES-PV-BIO", "city": "Bilbao", "region": "ES-PV", "lat": 43.2630, "lng": -2.9350},
        {"place_id": "ES-AN-MAL", "city": "Málaga", "region": "ES-AN", "lat": 36.7213, "lng": -4.4214},
        {"place_id": "ES-MC-MUR", "city": "Murcia", "region": "ES-MC", "lat": 37.9922, "lng": -1.1307},
        {"place_id": "ES-IB-PMI", "city": "Palma de Mallorca", "region": "ES-IB", "lat": 39.5696, "lng": 2.6502},
    ],
    "MX": [
        {"place_id": "MX-CMX-CDMX", "city": "Ciudad de México", "region": "MX-CMX", "lat": 19.4326, "lng": -99.1332},
        {"place_id": "MX-JAL-GDL", "city": "Guadalajara", "region": "MX-JAL", "lat": 20.6597, "lng": -103.3496},
        {"place_id": "MX-NLE-MTY", "city": "Monterrey", "region": "MX-NLE", "lat": 25.6866, "lng": -100.3161},
        {"place_id": "MX-PUE-PUE", "city": "Puebla", "region": "MX-PUE", "lat": 19.0414, "lng": -98.2063},
        {"place_id": "MX-ROO-CUN", "city": "Cancún", "region": "MX-ROO", "lat": 21.1619, "lng": -86.8515},
        {"place_id": "MX-GUA-LEO", "city": "León", "region": "MX-GUA", "lat": 21.1250, "lng": -101.6860},
        {"place_id": "MX-BCN-TIJ", "city": "Tijuana", "region": "MX-BCN", "lat": 32.5149, "lng": -117.0382},
        {"place_id": "MX-QUE-QRO", "city": "Querétaro", "region": "MX-QUE", "lat": 20.5881, "lng": -100.3899},
    ],
    "US": [
        {"place_id": "US-NY-NYC", "city": "New York City", "region": "US-NY", "lat": 40.7128, "lng": -74.0060},
        {"place_id": "US-CA-LA", "city": "Los Angeles", "region": "US-CA", "lat": 34.0522, "lng": -118.2437},
        {"place_id": "US-IL-CHI", "city": "Chicago", "region": "US-IL", "lat": 41.8781, "lng": -87.6298},
        {"place_id": "US-TX-HOU", "city": "Houston", "region": "US-TX", "lat": 29.7604, "lng": -95.3698},
        {"place_id": "US-FL-MIA", "city": "Miami", "region": "US-FL", "lat": 25.7617, "lng": -80.1918},
        {"place_id": "US-CA-SF", "city": "San Francisco", "region": "US-CA", "lat": 37.7749, "lng": -122.4194},
        {"place_id": "US-TX-DAL", "city": "Dallas", "region": "US-TX", "lat": 32.7767, "lng": -96.7970},
        {"place_id": "US-WA-SEA", "city": "Seattle", "region": "US-WA", "lat": 47.6062, "lng": -122.3321},
    ],
    "IT": [
        {"place_id": "IT-62-ROM", "city": "Roma", "region": "IT-62", "lat": 41.9028, "lng": 12.4964},
        {"place_id": "IT-25-MIL", "city": "Milano", "region": "IT-25", "lat": 45.4642, "lng": 9.1900},
        {"place_id": "IT-72-NAP", "city": "Napoli", "region": "IT-72", "lat": 40.8518, "lng": 14.2681},
        {"place_id": "IT-21-TUR", "city": "Torino", "region": "IT-21", "lat": 45.0703, "lng": 7.6869},
        {"place_id": "IT-82-PAL", "city": "Palermo", "region": "IT-82", "lat": 38.1157, "lng": 13.3615},
        {"place_id": "IT-52-FLR", "city": "Firenze", "region": "IT-52", "lat": 43.7696, "lng": 11.2558},
        {"place_id": "IT-45-BOL", "city": "Bologna", "region": "IT-45", "lat": 44.4949, "lng": 11.3426},
        {"place_id": "IT-34-VEN", "city": "Venezia", "region": "IT-34", "lat": 45.4408, "lng": 12.3155},
    ],
    "FR": [
        {"place_id": "FR-IDF-PAR", "city": "Paris", "region": "FR-IDF", "lat": 48.8566, "lng": 2.3522},
        {"place_id": "FR-ARA-LYO", "city": "Lyon", "region": "FR-ARA", "lat": 45.7640, "lng": 4.8357},
        {"place_id": "FR-PAC-MAR", "city": "Marseille", "region": "FR-PAC", "lat": 43.2965, "lng": 5.3698},
        {"place_id": "FR-OCC-TLS", "city": "Toulouse", "region": "FR-OCC", "lat": 43.6047, "lng": 1.4442},
        {"place_id": "FR-PAC-NCE", "city": "Nice", "region": "FR-PAC", "lat": 43.7102, "lng": 7.2620},
        {"place_id": "FR-NAQ-BDX", "city": "Bordeaux", "region": "FR-NAQ", "lat": 44.8378, "lng": -0.5792},
        {"place_id": "FR-BRE-RNS", "city": "Rennes", "region": "FR-BRE", "lat": 48.1173, "lng": -1.6778},
    ],
    "DE": [
        {"place_id": "DE-BE-BER", "city": "Berlin", "region": "DE-BE", "lat": 52.5200, "lng": 13.4050},
        {"place_id": "DE-HH-HAM", "city": "Hamburg", "region": "DE-HH", "lat": 53.5511, "lng": 9.9937},
        {"place_id": "DE-BY-MUC", "city": "München", "region": "DE-BY", "lat": 48.1351, "lng": 11.5820},
        {"place_id": "DE-NW-CGN", "city": "Köln", "region": "DE-NW", "lat": 50.9375, "lng": 6.9603},
        {"place_id": "DE-HE-FRA", "city": "Frankfurt am Main", "region": "DE-HE", "lat": 50.1109, "lng": 8.6821},
        {"place_id": "DE-BW-STR", "city": "Stuttgart", "region": "DE-BW", "lat": 48.7758, "lng": 9.1829},
        {"place_id": "DE-NW-DUS", "city": "Düsseldorf", "region": "DE-NW", "lat": 51.2277, "lng": 6.7735},
    ],
    "GB": [
        {"place_id": "GB-ENG-LON", "city": "London", "region": "GB-ENG", "lat": 51.5074, "lng": -0.1278},
        {"place_id": "GB-ENG-MAN", "city": "Manchester", "region": "GB-ENG", "lat": 53.4808, "lng": -2.2426},
        {"place_id": "GB-ENG-BHX", "city": "Birmingham", "region": "GB-ENG", "lat": 52.4862, "lng": -1.8904},
        {"place_id": "GB-ENG-LIV", "city": "Liverpool", "region": "GB-ENG", "lat": 53.4084, "lng": -2.9916},
        {"place_id": "GB-SCT-EDI", "city": "Edinburgh", "region": "GB-SCT", "lat": 55.9533, "lng": -3.1883},
        {"place_id": "GB-SCT-GLA", "city": "Glasgow", "region": "GB-SCT", "lat": 55.8642, "lng": -4.2518},
        {"place_id": "GB-WLS-CWL", "city": "Cardiff", "region": "GB-WLS", "lat": 51.4816, "lng": -3.1791},
    ],
    "CO": [
        {"place_id": "CO-DC-BOG", "city": "Bogotá", "region": "CO-DC", "lat": 4.7110, "lng": -74.0721},
        {"place_id": "CO-ANT-MED", "city": "Medellín", "region": "CO-ANT", "lat": 6.2442, "lng": -75.5812},
        {"place_id": "CO-VAC-CLO", "city": "Cali", "region": "CO-VAC", "lat": 3.4516, "lng": -76.5320},
        {"place_id": "CO-ATL-BAQ", "city": "Barranquilla", "region": "CO-ATL", "lat": 10.9639, "lng": -74.7964},
        {"place_id": "CO-BOL-CTG", "city": "Cartagena", "region": "CO-BOL", "lat": 10.3910, "lng": -75.4794},
    ],
}

def get_country_name(country_code: str, language: str = 'es') -> str:
    """Get localized country name"""
    country = COUNTRIES.get(country_code.upper())
    if country:
        return country['name'].get(language, country['name'].get('en', country_code))
    return country_code

def get_regions_for_country(country_code: str) -> list:
    """Get list of regions for a country"""
    return REGIONS.get(country_code.upper(), [])

def get_cities_for_country(country_code: str) -> list:
    """Get list of cities for a country"""
    return CITIES.get(country_code.upper(), [])

def search_places(query: str, country_code: str = None, limit: int = 10) -> list:
    """
    Search for places matching query.
    Returns list of PlaceSearchResult-compatible dicts.
    """
    query_lower = query.lower().strip()
    results = []
    
    # Determine which countries to search
    countries_to_search = [country_code.upper()] if country_code else list(CITIES.keys())
    
    for cc in countries_to_search:
        cities = CITIES.get(cc, [])
        regions = {r['code']: r['name'] for r in REGIONS.get(cc, [])}
        country_name = get_country_name(cc, 'es')
        
        for city_data in cities:
            city_name = city_data['city']
            region_code = city_data['region']
            region_name = regions.get(region_code, region_code)
            
            # Match against city name, region name
            if (query_lower in city_name.lower() or 
                query_lower in region_name.lower()):
                
                label = f"{city_name}, {region_name}, {country_name}"
                results.append({
                    "place_id": city_data['place_id'],
                    "label": label,
                    "city_name": city_name,
                    "region_name": region_name,
                    "country_code": cc,
                    "latitude": city_data['lat'],
                    "longitude": city_data['lng']
                })
                
                if len(results) >= limit:
                    return results
    
    return results
